[tool.poetry]
name = "miuc"
version = "0.1.15"
description = "Markdown Intelligence Url Complete"
authors = ["luzhixing12345 <luzhixing12345@163.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/luzhixing12345/miuc"
documentation = "https://luzhixing12345.github.io/miuc/"

[tool.poetry.dependencies]
python = "^3.7"
requests = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
miuc = 'miuc.main:main'